const {
  IMAGE_OMITTED_NOTE,
  visionFromModelEntry,
  modelSupportsVision,
  hasImageAttachments,
  stripImageAttachments,
  hasImageContent,
  stripImageContent,
} = require("../../../utils/helpers/modelVision");

const image = {
  name: "image.png",
  mime: "image/png",
  contentString: "data:image/png;base64,AAAA",
};
const audio = {
  name: "clip.mp3",
  mime: "audio/mpeg",
  contentString: "data:audio/mpeg;base64,BBBB",
};

// The shapes llama.cpp's router mode reports, as generated by fetch-models.sh.
const textOnlyPreset = {
  id: "qwen3.8-27b",
  status: {
    value: "unloaded",
    preset:
      "[qwen3.8-27b]\nmodel = /models/Qwen3.8-27B-UD-Q4_K_XL.gguf\nctx-size = 16384\n\n",
  },
  architecture: { input_modalities: ["text"], output_modalities: ["text"] },
};
const visionPreset = {
  id: "gemma-4-12b",
  status: {
    value: "unloaded",
    preset:
      "[gemma-4-12b]\nmodel = /models/gemma-4-12b-it-qat-q4_0.gguf\nctx-size = 16384\nmmproj = /models/mmproj-gemma-4-12b-it-qat-q4_0.gguf\n\n",
  },
  // Deliberately text-only: an mmproj in the preset must win over this.
  architecture: { input_modalities: ["text"], output_modalities: ["text"] },
};

describe("visionFromModelEntry", () => {
  it("is false for a text-only llama.cpp preset", () => {
    expect(visionFromModelEntry(textOnlyPreset)).toBe(false);
  });

  it("is true when the preset has an mmproj, whatever the modalities say", () => {
    expect(visionFromModelEntry(visionPreset)).toBe(true);
  });

  it("reads an mmproj from the launch args", () => {
    expect(
      visionFromModelEntry({
        status: { args: ["/app/llama-server", "--mmproj", "/models/x.gguf"] },
      })
    ).toBe(true);
    expect(
      visionFromModelEntry({ status: { args: ["-mm", "/models/x.gguf"] } })
    ).toBe(true);
  });

  it("is false when mmproj is switched off", () => {
    expect(
      visionFromModelEntry({
        status: { args: ["--hf-repo", "org/model", "--no-mmproj"] },
        architecture: { input_modalities: ["text", "image"] },
      })
    ).toBe(false);
  });

  it("falls back to the reported input modalities", () => {
    expect(
      visionFromModelEntry({
        architecture: { input_modalities: ["text", "image"] },
      })
    ).toBe(true);
    expect(
      visionFromModelEntry({ architecture: { input_modalities: ["text"] } })
    ).toBe(false);
  });

  it("is null when the entry says nothing", () => {
    expect(visionFromModelEntry({ id: "gpt-4o", object: "model" })).toBe(null);
    expect(visionFromModelEntry(undefined)).toBe(null);
  });
});

describe("modelSupportsVision", () => {
  const listModels = async () => [textOnlyPreset, visionPreset];

  it("answers per model from the model list", async () => {
    expect(await modelSupportsVision("qwen3.8-27b", { listModels })).toBe(
      false
    );
    expect(await modelSupportsVision("gemma-4-12b", { listModels })).toBe(
      true
    );
  });

  it("matches a model by alias", async () => {
    const aliased = { ...textOnlyPreset, id: "full-name", aliases: ["short"] };
    expect(
      await modelSupportsVision("short", { listModels: async () => [aliased] })
    ).toBe(false);
  });

  it("keeps sending images when it cannot tell", async () => {
    expect(await modelSupportsVision("missing", { listModels })).toBe(true);
    expect(
      await modelSupportsVision("qwen3.8-27b", { listModels: async () => null })
    ).toBe(true);
    expect(
      await modelSupportsVision("gpt-4o", {
        listModels: async () => [{ id: "gpt-4o" }],
      })
    ).toBe(true);
  });
});

describe("agent messages (attachments)", () => {
  it("detects images but not audio", () => {
    expect(hasImageAttachments([{ content: "a", attachments: [image] }])).toBe(
      true
    );
    expect(hasImageAttachments([{ content: "a", attachments: [audio] }])).toBe(
      false
    );
    expect(hasImageAttachments([{ content: "a" }])).toBe(false);
  });

  it("drops images, keeps audio, and notes the omission", () => {
    const messages = [
      { role: "system", content: "sys" },
      { role: "user", content: "old", attachments: [image] },
      { role: "assistant", content: "reply" },
      { role: "user", content: "new", attachments: [image, audio] },
    ];
    const stripped = stripImageAttachments(messages);

    expect(stripped[0]).toBe(messages[0]);
    expect(stripped[1]).toEqual({
      role: "user",
      content: `old\n\n${IMAGE_OMITTED_NOTE}`,
    });
    expect(stripped[3]).toEqual({
      role: "user",
      content: `new\n\n${IMAGE_OMITTED_NOTE}`,
      attachments: [audio],
    });
    expect(hasImageAttachments(stripped)).toBe(false);
  });
});

describe("chat messages (OpenAI content parts)", () => {
  it("detects image_url parts", () => {
    expect(
      hasImageContent([
        {
          role: "user",
          content: [
            { type: "text", text: "hi" },
            { type: "image_url", image_url: { url: image.contentString } },
          ],
        },
      ])
    ).toBe(true);
    expect(hasImageContent([{ role: "user", content: "hi" }])).toBe(false);
    expect(hasImageContent(null)).toBe(false);
  });

  it("collapses a text-only remainder back to a string", () => {
    const [message] = stripImageContent([
      {
        role: "user",
        content: [
          { type: "text", text: "describe this" },
          { type: "image_url", image_url: { url: image.contentString } },
        ],
      },
    ]);
    expect(message).toEqual({
      role: "user",
      content: `describe this\n\n${IMAGE_OMITTED_NOTE}`,
    });
  });

  it("keeps non-image parts in array form", () => {
    const audioPart = { type: "input_audio", input_audio: { data: "BBBB" } };
    const [message] = stripImageContent([
      {
        role: "user",
        content: [
          { type: "text", text: "listen" },
          audioPart,
          { type: "image_url", image_url: { url: image.contentString } },
        ],
      },
    ]);
    expect(message.content).toEqual([
      { type: "text", text: "listen" },
      audioPart,
      { type: "text", text: IMAGE_OMITTED_NOTE },
    ]);
  });

  it("leaves messages without images untouched", () => {
    const messages = [{ role: "user", content: "hi" }];
    expect(stripImageContent(messages)[0]).toBe(messages[0]);
  });
});
